import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/NavBar";
import Footer from "@/components/ui/Footer";
import BottomNavbar from "@/components/ui/BottomNavbar";
import StoreProvider from "../providers/StoreProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import TanstackProvider from "@/providers/TanstackProvider";
import Provider from "@/components/HOC/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <div className="hidden md:block sticky top-0 z-50">
            <NavBar />
          </div>
          <div className="block md:hidden">
            <BottomNavbar />
          </div>
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
